### PR TITLE
Fix and test bootswatch override  

### LINKED ISSUE #75: Add tests with mathjax and boostwatch
Our wrapper needs to overwrite the `template:params` however I keep breaking one case when fixing another.

It seems that if we pass a list() in our overrides, the params merge (instead of replace) the ones from the `_pkgdown.yml`. In this scenario we get an error like [here](https://github.com/r-universe/ropensci/runs/4828538553?check_suite_focus=true).

```
Error : Can't find Bootswatch theme 'readable' (template.bootswatch in '_pkgdown.yml') for Bootstrap version '5' (template.bootstrap in '_pkgdown.yml')
```

So instead [I tried to set](https://github.com/ropensci-org/rotemplate/commit/6db9cb50c34780d33c9299a6cfb3240545a0c099) `params=NULL` in our overrides and manually set mathjax = TRUE later in the wrapper, but then I found out this had broken our mathjax docs again.

So now I reverted it again, but we really need unit tests that test at least these two scenarios.

### PR DESCRIPTION
**Pull request by maelle**
Fix #75

### CODE REVIEW

File: R/build-site.R [hunk 1]
```diff
@@ -37,6 +39,8 @@ build_ropensci_docs <- function(path = ".", destination = NULL, install = FALSE,
     destination = destination
   )
 
+  find_and_fix_readme(path, pkgname)
```
Comment (maelle) [inline R/build-site.R:41]: @jeroen this is something my previous PR had mistakenly removed.
